# Generated by Django 4.1 on 2023-05-12 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="姓名")),
                ("phone", models.CharField(max_length=100, verbose_name="手机号")),
                ("sex", models.CharField(default="男", max_length=2, verbose_name="性别")),
                (
                    "id_number",
                    models.CharField(max_length=18, null=True, verbose_name="身份证号"),
                ),
                (
                    "status",
                    models.IntegerField(default=1, max_length=11, verbose_name="账号状态"),
                ),
                (
                    "create_time",
                    models.DateField(auto_now_add=True, verbose_name="创建时间"),
                ),
                ("update_time", models.DateField(auto_now=True, verbose_name="更新时间")),
            ],
            options={
                "db_table": "why_users",
                "ordering": ["id"],
            },
        ),
    ]
