# Generated by Django 4.1 on 2023-05-12 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App_user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="status",
            field=models.IntegerField(default=1, verbose_name="账号状态"),
        ),
    ]
