# Generated by Django 4.1 on 2023-05-12 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App_user", "0002_alter_users_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="create_time",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="users",
            name="update_time",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
    ]
